version: '2'

services:
  # rescue_db:
  #   container_name: wp-mysql-rescue
  #   ports:
  #     - 8090:3306
  #   image: mysql/mysql-server:5.7
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Spl3sh27?
  #   volumes:
  #     - ./data/db/mysql:/var/lib/mysql
  #     - ./conf.d:/etc/mysql/conf.d

  db:
    container_name: wp-mysql
    ports:
      - 8086:3306
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: uc-wordpress
      MYSQL_ROOT_PASSWORD: Spl3sh27?
    volumes:
      # - ./data/db/mysql-dev:/var/lib/mysql
      - ./data/db/mysql:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    # networks:
    #   vmnet:
    #     ipv4_address: 4.11.0.3

  wp: 
    container_name: uc-wordpress
    environment:
      WORDPRESS_DB_NAME: uc-wordpress
      WORDPRESS_DB_HOST: db:3306
      # create these credentials manually after the initialization of the database i.e. 'crud'@'%'
      WORDPRESS_DB_USER: crud
      WORDPRESS_DB_PASSWORD: Spl3sh27?
    ports:
      - 7310:80
    restart: unless-stopped
    image: uchilaka/uc-wordpress:dev
    build:
      context: .
    volumes:
      # - ./data/wordpress-dev:/var/www/html
      - ./data/wordpress:/var/www/html
    depends_on: 
      - db
    # command: ["/usr/shared/app/node_modules/wait-for-it/wait-for-it.sh", "db:3306", "--", "apache2-foreground"]
    # networks:
    #   vmnet:
    #     ipv4_address: 4.11.0.11

# networks:
#   vmnet:
#     driver: bridge
#     ipam:
#       config:
#         - subnet:  4.11.0.0/16
#           gateway: 4.11.0.1

