#!/bin/bash
WDIR=$(pwd)
DATAPATH=$(pwd)/data/wordpress
LOGFILE=$(pwd)/logs/$(date "+%Y%m%d_%H00").txt

# Include external variables 
source $WDIR/private/vars.conf

echo "Database config -> mysql://${WP_MYSQL_HOST}/${WP_MYSQL_DB};username=${WP_MYSQL_USER};password=${WP_MYSQL_PWD}"

if ! [ -d $DATAPATH ]; then
    logger -s "Creating $DATAPATH" 2>> $LOGFILE
    mkdir -p $DATAPATH
else
    echo "Found data directory: $DATAPATH"
fi

# log location for current container
logger -s "Will persist (latest) container app data @ $DATAPATH..." 2>> $LOGFILE

# @IMPORTANT define the $WP_MYSQL_... variables in private/vars. This WILL NOT exist in a 
# new deployment on the docker engine
docker run --name $WP_CONTAINER_NAME \
-e WORDPRESS_DB_HOST=$WP_MYSQL_HOST -e WORDPRESS_DB_NAME=$WP_MYSQL_DB \
-e WORDPRESS_DB_USER=$WP_MYSQL_USER -e WORDPRESS_DB_PASSWORD=$WP_MYSQL_PWD \
-v $DATAPATH/www:/var/www/html \
-p $WWW_PORT:80 \
--restart unless-stopped \
-d uchilaka/wordpress:dev