#!/bin/bash
wget --quiet --output-document=wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar
php wp-cli.phar --info && mv wp-cli.phar /usr/local/bin/wp
echo "WP-CLI available? $(which wp)"
